# Generated by Django 4.2.8 on 2023-12-31 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("details", models.CharField(max_length=500)),
                ("date", models.DateField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Coordinators",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cord_name", models.CharField(max_length=200)),
                ("cord_num", models.IntegerField()),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.events")),
            ],
        ),
    ]
