# Generated by Django 4.2.8 on 2023-12-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinators",
            name="cord_num",
            field=models.CharField(),
        ),
    ]
