# Generated by Django 4.2.8 on 2023-12-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_coordinators_cord_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinators",
            name="event",
        ),
        migrations.AddField(
            model_name="coordinators",
            name="event",
            field=models.ManyToManyField(related_name="cords", to="api.events"),
        ),
    ]
