# Generated by Django 4.2.8 on 2023-12-31 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_coordinators_event_coordinators_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinators",
            name="event",
        ),
        migrations.AddField(
            model_name="coordinators",
            name="event",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="cords", to="api.events"
            ),
            preserve_default=False,
        ),
    ]
