# Generated by Django 4.2.8 on 2023-12-31 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_coordinators_event_coordinators_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posters",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("link", models.CharField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posters", to="api.events"
                    ),
                ),
            ],
        ),
    ]
